# Copyright Contributors to the Open Cluster Management project

apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: cm
spec:
  version: {{ .TagName }}
  homepage: https://github.com/open-cluster-management/cm-cli
  shortDescription: Provides commands to interract with OCM/ACM to provision and managed your Hybrid Cloud presence from the command-line,
  description: |
    This plugin allows you to take several actions on an OCM/ACM environment such as 
    create/delete/attach/detach nanaged clusters or managed clusterpools.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/open-cluster-management/cm-cli/releases/download/{{ .TagName }}/cm_darwin_amd64.tar.gz" .TagName }}
    bin: cm
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/open-cluster-management/cm-cli/releases/download/{{ .TagName }}/cm_linux_amd64.tar.gz" .TagName }}
    bin: cm
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/open-cluster-management/cm-cli/releases/download/{{ .TagName }}/cm_linux_arm64.tar.gz" .TagName }}
    bin: cm
  - selector:
      matchLabels:
        os: linux
        arch: ppc64ie
    {{addURIAndSha "https://github.com/open-cluster-management/cm-cli/releases/download/{{ .TagName }}/cm_linux_ppc64le.tar.gz" .TagName }}
    bin: cm
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/open-cluster-management/cm-cli/releases/download/{{ .TagName }}/cm_linux_s390x.tar.gz" .TagName }}
    bin: cm
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/open-cluster-management/cm-cli/releases/download/{{ .TagName }}/cm_windows_amd64.zip" .TagName }}
    bin: cm
