# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
metadata:
  name: "{{ .clusterPool.name }}"
baseDomain: {{ .clusterPool.azure.baseDnsDomain }}
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: {{ if .clusterPool.master }}{{ .clusterPool.master.replicas }}{{ else }}3{{end}}
  platform:
    azure:
      osDisk:
        diskSizeGB: 128
      type:  Standard_D4s_v3
compute:
- hyperthreading: Enabled
  name: worker
  replicas: {{ if .clusterPool.worker }}{{ .clusterPool.worker.replicas }}{{ else }}3{{end}}
  platform:
    azure:
      type:  Standard_D2s_v3
      osDisk:
        diskSizeGB: 128
      zones:
      - "1"
      - "2"
      - "3"
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork: 
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: {{ .clusterPool.azure.baseDomainRGN }}
    region: {{ .clusterPool.azure.region }}
pullSecret: "" # skip, hive will inject based on it's secrets
{{- if .clusterPool.sshPublicKey }}
sshKey: |-
{{ .clusterPool.sshPublicKey | indent 4 }}
{{- end }}