# Copyright Contributors to the Open Cluster Management project

apiVersion: hive.openshift.io/v1
kind: ClusterPool
metadata:
  name: "{{ .clusterPool.name }}"
  namespace: "{{ .namespace }}"
  labels:
{{- if .clusterPool.cloud }}
    cloud: {{ .clusterPool.cloud }}
{{- end }}
{{- if .clusterPool.vendor }}
    vendor: {{ .clusterPool.vendor }}
{{- end }}
{{- if .clusterPool.clusterSetName }}
    cluster.open-cluster-management.io/clusterset: {{ .clusterPool.clusterSetName }}
{{- end }}
spec:
  size: {{ .clusterPool.size }}
{{- if .clusterPool.worker }}
{{- if (eq (toString (.clusterPool.worker.replicas)) "0") }}
  skipMachinePools: true
{{- end }}
{{- end }}
{{- if (eq .clusterPool.cloud "aws") }}
  baseDomain: {{ .clusterPool.aws.baseDnsDomain }}
{{- end }}
{{- if (eq .clusterPool.cloud "azure") }}
  baseDomain: {{ .clusterPool.azure.baseDnsDomain }}
{{- end }}
{{- if (eq .clusterPool.cloud "gcp") }}
  baseDomain: {{ .clusterPool.gcp.baseDnsDomain }}
{{- end }}
  installConfigSecretTemplateRef:
    name: {{ .clusterPool.name }}-install-config
  imageSetRef:
{{ if .clusterPool.imageSetRef }}
    name: {{ .clusterPool.imageSetRef }}
{{ else }}
    name: {{ include "ocpImage" . }}
{{- end }}
  pullSecretRef:
    name: {{ .clusterPool.name }}-pull-secret
  platform:
{{- if (eq .clusterPool.cloud "aws") }}
    aws:
      region: {{ .clusterPool.aws.region }}
{{- end }}
{{- if (eq .clusterPool.cloud "azure") }}
    azure:
      baseDomainResourceGroupName: {{ .clusterPool.azure.baseDomainRGN }}
      region: {{ .clusterPool.azure.region }}
{{- end }}
{{- if (eq .clusterPool.cloud "gcp") }}
    gcp:
      region: {{ .clusterPool.gcp.region }}
{{- end }}
      credentialsSecretRef:
        name: "{{ .clusterPool.name }}-creds"
