# Copyright Contributors to the Open Cluster Management project

clusterPool:
  size: 1 #Number of cluster in the pool
  master: 
    replicas: 3 #Number of master node, default 3
  worker:
    replicas: 3 #Number of worker node, default 3
  name: #<clusterpool-name>, this value is overwritten by the --cluster parameter
  labels: # map of custom labels, cloud and vendor labels will be overwritten by the cloud and vendor attribute below.
    #mylabel: myvalue
  cloud: vsphere # clouds values can be aws, azure, gcp, openstack, vsphere
  vendor: OpenShift
  #clusterSetName the name of the clusterset
  #clusterSetname: 
  #ocpImage and imageSetRef are mutually exclusive.
  ocpImage: # ocp image (ie: quay.io/openshift-release-dev/ocp-release:4.3.40-x86_64)
  imageSetRef: # the imageSetRef, use `oc get clusterimageset` to find the list, use this when you don't have the permission to create clusterimageset.
  #imagepullsecret in format:
  # {
  # "auths": {
  #   "quay.io": {
  #     "auth": "xxxxxxx",
  #     "email": ""
  #   }
  # }
  imagePullSecret: |- 
    pullSecret
  sshPublicKey: |-
    Public key
  aws:
    baseDnsDomain: # baseDomain of your cluster (ie: mycompany.com)
    awsAccessKeyID:
    awsSecretAccessKeyID:
    region: # Region (ie: us-east-1)
    master:
      type: m5.xlarge
      rootVolume: # see below the default values 
        iops: 4000
        size: 100
        type: gp2
    worker:
      type: m5.xlarge
      rootVolume: # see below the default values 
        iops: 2000
        size: 100
        type: gp2
  azure:
    baseDnsDomain: # baseDomain of your cluster (ie: mycompany.com)
    baseDomainRGN:
    clientID:
    clientSecret:
    tenantID:
    subscriptionID:
    region:
  gcp:
    osServiceAccountJson: |-
      {
        your authentication
      }
    projectID:
    baseDnsDomain:
    region:
