# Copyright Contributors to the Open Cluster Management project

managedCluster:
  master: 
    replicas: 3 #Number of master node, default 3
  worker:
    replicas: 3 #Number of worker node, default 3
  name: #<cluster-name>, this value is overwritten by the --cluster parameter
  installAttemptsLimit: 1
  labels: # map of custom labels, cloud and vendor labels will be overwritten by the cloud and vendor attribute below.
    #mylabel: myvalue
  cloud: vsphere # clouds values can be aws, azure, gcp, openstack, vsphere
  vendor: OpenShift
  #clusterSetName the name of the clusterset
  #clusterSetname: 
  ocpImage: # ocp image (ie: quay.io/openshift-release-dev/ocp-release:4.3.40-x86_64)
  imageSetRef: # the imageSetRef, use `oc get clusterimageset` to find the list, use this when you don't have the permission to create clusterimageset.
  addons:
    applicationManager:
      enabled: true
      argocdCluster: false
    policyController:
      enabled: true
    searchCollector:
      enabled: true
    certPolicyController:
      enabled: true
    iamPolicyController:
      enabled: true
  sshPublicKey: |-
    Public key
  sshPrivateKey: |-
    -----BEGIN RSA PRIVATE KEY-----
    private key
    -----END RSA PRIVATE KEY-----
  aws:
    baseDnsDomain: # baseDomain of your cluster (ie: mycompany.com)
    awsAccessKeyID:
    awsSecretAccessKeyID:
    region: # Region (ie: us-east-1)
    master:
      type: m5.xlarge
      rootVolume: # see below the default values 
        iops: 4000
        size: 100
        type: gp2
    worker:
      type: m5.xlarge
      rootVolume: # see below the default values 
        iops: 2000
        size: 100
        type: gp2
  azure:
    baseDnsDomain: # baseDomain of your cluster (ie: mycompany.com)
    baseDomainRGN:
    clientID:
    clientSecret:
    tenantID:
    subscriptionID:
    region:
  gcp:
    osServiceAccountJson: |-
      {
        your authentication
      }
    projectID:
    baseDnsDomain:
    region:
  vsphere:
    username:
    password:
    vcenter:
    cacertificate: |-
      -----BEGIN CERTIFICATE-----
      vSphere certificate
      -----END CERTIFICATE-----
    cluster:
    datacenter:
    datastore:
    network:
    baseDnsDomain: # baseDomain of your cluster (ie: mycompany.com)
    apiVIP:
    ingressVIP:
  openstack:
    baseDnsDomain: # baseDomain of your cluster (ie: mycompany.com)
    cloudsYaml: |-
      clouds:
        openstack:
          auth:
    cloud:
    externalNetwork:
    apiFloatingIP:
    ingressFloatingIP:
    masterFlavor:
    workerFlavor:
    machineNetworkCIDR:  
