# Copyright Contributors to the Open Cluster Management project

{{- if .managedCluster.ocpImage }}
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: {{ include "ocpImage" . }}
spec:
  releaseImage: {{  .managedCluster.ocpImage }}
{{- end }}