# Copyright Contributors to the Open Cluster Management project

{{- if (eq .managedCluster.cloud "vsphere") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .managedCluster.name }}-vsphere-certs
  namespace: "{{ .managedCluster.name }}"
data:
  .cacert: {{ .managedCluster.vsphere.cacertificate | b64enc }}
type: Opaque
{{- end }}
