# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
metadata:
  name: "{{ .clusterPool.name }}"
baseDomain: {{ .clusterPool.gcp.baseDnsDomain }}
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: {{ if .clusterPool.master }}{{ .clusterPool.master.replicas }}{{ else }}3{{end}}
  platform:
    gcp:
      type: n1-standard-4
compute:
- hyperthreading: Enabled
  replicas: {{ if .clusterPool.worker }}{{ .clusterPool.worker.replicas }}{{ else }}3{{end}}
  platform:
    gcp:
      type: n1-standard-4
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  gcp:
    projectID: {{ .clusterPool.gcp.projectID }}
    region: {{ .clusterPool.gcp.region }}
pullSecret: "" # skip, hive will inject based on it's secrets
{{- if .clusterPool.sshPublicKey }}
sshKey: |-
{{ .clusterPool.sshPublicKey | indent 4 }}
{{- end }}