# Copyright Contributors to the Open Cluster Management project

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build project
        run: |
          make build-bin
      - name: Release
        uses: softprops/action-gh-release@v0.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: CHANGELOG.md
          files: |
            docs/help.tar.gz
            docs/help.zip
            bin/cm_darwin_amd64.tar.gz
            bin/cm_linux_amd64.tar.gz
            bin/cm_linux_arm64.tar.gz
            bin/cm_linux_ppc64le.tar.gz
            bin/cm_linux_s390x.tar.gz
            bin/cm_windows_amd64.zip
          draft: true
          prerelease: false
